#true features to use
UID = 1
NUM_LIKES_PER_NUM_FRIENDS = 1
FOLLOW_FRIENDS_RATIO = 1
MAX_TIME_BW_TWEETS = 1
RE_PER_TWEET = 1
NUM_LIKES = 1
NUM_LIKES_PER_FOLLOWER = 1
AGE_ACCOUNT = 1
NUM_TWEETS = 1
LOCATION = 1
LEN_USERNAME = 1
HAS_PHOTO = 1
LIKES_PER_DAY = 1

to_append = (
    UID, 
    NUM_LIKES_PER_NUM_FRIENDS, 
    FOLLOW_FRIENDS_RATIO, 
    MAX_TIME_BW_TWEETS, 
    RE_PER_TWEET, 
    NUM_LIKES, 
    NUM_LIKES_PER_FOLLOWER, 
    AGE_ACCOUNT, 
    NUM_TWEETS, 
    LOCATION, 
    LEN_USERNAME, 
    HAS_PHOTO, 
    LIKES_PER_DAY
)